centroid_file_list,'/scratch/adam_work/texts/meredith_0707_ptg_radec_maplist.txt','/scratch/adam_work/texts/meredith_0707_ptg_radec_centroids_111.txt'
centroid_plots,'/scratch/adam_work/texts/meredith_0707_ptg_radec_centroids_111.txt','0707','meredith_ptg_radec_111'
centroid_file_list,'/scratch/adam_work/texts/meredith_0707_pca_radec_maplist.txt','/scratch/adam_work/texts/meredith_0707_pca_radec_centroids_111.txt'
centroid_plots,'/scratch/adam_work/texts/meredith_0707_pca_radec_centroids_111.txt','0707','meredith_pca_radec_111'
centroid_file_list,'/scratch/adam_work/texts/meredith_0707_minus_radec_maplist.txt','/scratch/adam_work/texts/meredith_0707_minus_radec_centroids_111.txt'
centroid_plots,'/scratch/adam_work/texts/meredith_0707_minus_radec_centroids_111.txt','0707','meredith_minus_radec_111'

centroid_file_list,'/scratch/adam_work/texts/meredith_0707_ptg_radec_maplist.txt','/scratch/adam_work/texts/meredith_0707_ptg_radec_centroids_011.txt',precess=0,aberration=1,nutate=1
centroid_plots,'/scratch/adam_work/texts/meredith_0707_ptg_radec_centroids_011.txt','0707','meredith_ptg_radec_011'
centroid_file_list,'/scratch/adam_work/texts/meredith_0707_ptg_radec_maplist.txt','/scratch/adam_work/texts/meredith_0707_ptg_radec_centroids_001.txt',precess=0,aberration=0,nutate=1
centroid_plots,'/scratch/adam_work/texts/meredith_0707_ptg_radec_centroids_001.txt','0707','meredith_ptg_radec_001'
centroid_file_list,'/scratch/adam_work/texts/meredith_0707_ptg_radec_maplist.txt','/scratch/adam_work/texts/meredith_0707_ptg_radec_centroids_010.txt',precess=0,aberration=1,nutate=0
centroid_plots,'/scratch/adam_work/texts/meredith_0707_ptg_radec_centroids_010.txt','0707','meredith_ptg_radec_010'
centroid_file_list,'/scratch/adam_work/texts/meredith_0707_ptg_radec_maplist.txt','/scratch/adam_work/texts/meredith_0707_ptg_radec_centroids_000.txt',precess=0,aberration=0,nutate=0
centroid_plots,'/scratch/adam_work/texts/meredith_0707_ptg_radec_centroids_000.txt','0707','meredith_ptg_radec_000'
centroid_file_list,'/scratch/adam_work/texts/meredith_0707_ptg_radec_maplist.txt','/scratch/adam_work/texts/meredith_0707_ptg_radec_centroids_101.txt',precess=1,aberration=0,nutate=1
centroid_plots,'/scratch/adam_work/texts/meredith_0707_ptg_radec_centroids_101.txt','0707','meredith_ptg_radec_101'
centroid_file_list,'/scratch/adam_work/texts/meredith_0707_ptg_radec_maplist.txt','/scratch/adam_work/texts/meredith_0707_ptg_radec_centroids_110.txt',precess=1,aberration=1,nutate=0
centroid_plots,'/scratch/adam_work/texts/meredith_0707_ptg_radec_centroids_110.txt','0707','meredith_ptg_radec_110'
centroid_file_list,'/scratch/adam_work/texts/meredith_0707_ptg_radec_maplist.txt','/scratch/adam_work/texts/meredith_0707_ptg_radec_centroids_100.txt',precess=1,aberration=0,nutate=0
centroid_plots,'/scratch/adam_work/texts/meredith_0707_ptg_radec_centroids_100.txt','0707','meredith_ptg_radec_100'
