array_params   = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/array_params_jun05.txt'
bolo_params    = '/home/milkyway/student/ginsbura/array_params/bolo_params_jun05.txt'
beam_locations_jul05 = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/beam_locations_jul05.txt'
beam_locations_default = '/scratch/adam_work/beam_locations_default.txt'
filelist       = '/scratch/sliced_polychrome/3c273/3c273_0506_list.txt'


array_params_jun05     = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/array_params_jun05.txt'
array_params_jul05     = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/array_params_jul05.txt'
array_params_nov06     = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/array_params_nov06.txt'
array_params_jun06     = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/array_params_jun06_rotating.txt'
array_params_jan07     = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/array_params_jan07_60as.txt'
array_params_jan07     = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/array_params_jan07.txt'
array_params_feb07     = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/array_params_feb07_60as.txt'
array_params_feb07     = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/array_params_feb07.txt'
array_params_jun07     = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/array_params_jun07.txt'
array_params_sep07     = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/array_params_sep07_no_rot.txt'
array_params_sep07_rot = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/array_params_sep07.txt'

bolo_params_feb05      = '/home/milkyway/student/ginsbura/array_params/bolo_params_feb05.txt'
bolo_params_jun05      = '/home/milkyway/student/ginsbura/array_params/bolo_params_jun05.txt'
bolo_params_sep05      = '/home/milkyway/student/ginsbura/array_params/bolo_params_sep05.txt'
bolo_params_jun06      = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/bolo_params_jun06.txt'
bolo_params_nov06      = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/bolo_params_nov06.txt'
bolo_params_jan07      = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/bolo_params_jan07.txt'
bolo_params_jun07      = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/bolo_params_jun07_mmd.txt'
bolo_params_jun07      = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/bolo_params_jun07.txt'
bolo_params_sep07      = '/home/milkyway/student/ginsbura/bolocam_cvs/pipeline/cleaning/parameters/bolo_params_sep07.txt'


